platform :ios, '8.0'
use_frameworks!

target 'IntoRobotSDKDemo' do

pod 'SDWebImage'		        #source     https://github.com/rs/SDWebImage
pod 'AFNetworking'			    #source     https://github.com/AFNetworking/AFNetworking/
pod 'MQTTClient'                #source     https://github.com/ckrey/MQTT-Client-Framework
pod 'CocoaAsyncSocket'          #source     https://github.com/robbiehanson/CocoaAsyncSocket

end